from __future__ import annotations
import random
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from .grid_engine import GridEngine

class ImpactPredictor:
    """Lightweight scenario-impact predictor for the prototype.

    It is trained on simulated scenarios generated by the same transparent
    grid engine. This is a prototype ML layer; later replace the training set
    with real historical/SCADA-derived events.
    """
    def __init__(self):
        self.model = RandomForestClassifier(n_estimators=160, max_depth=8, random_state=42, class_weight="balanced")
        self.line_ids = list(GridEngine().lines.keys())
        self._train()

    def features(self, line_id: str, load_scale: float):
        e = GridEngine()
        line = e.lines[line_id]
        return [
            self.line_ids.index(line_id),
            line.capacity_mw,
            1 if line.tie else 0,
            line.reactance,
            load_scale,
            e.critical_load() * load_scale,
            e.total_load() * load_scale,
        ]

    def _train(self):
        X=[]; y=[]
        for _ in range(700):
            line_id=random.choice(self.line_ids[:-1])
            load_scale=random.uniform(0.75,1.25)
            e=GridEngine(); e.load_scale=load_scale; e.inject_failure(line_id)
            r=e.power_flow()
            risk = 1 if (r['critical_unserved_mw'] > 0.1 or r['unserved_mw'] > 20 or r['overloaded_lines'] > 2) else 0
            X.append(self.features(line_id,load_scale)); y.append(risk)
        self.model.fit(np.array(X), np.array(y))

    def predict(self, line_id: str, load_scale: float=1.0):
        x=np.array([self.features(line_id,load_scale)])
        probs=self.model.predict_proba(x)[0]; prob=float(probs[list(self.model.classes_).index(1)]) if 1 in self.model.classes_ else 0.0
        label='HIGH' if prob>=0.66 else 'MEDIUM' if prob>=0.33 else 'LOW'
        return {'risk':label,'probability':round(prob,3),'model':'RandomForest scenario-impact predictor'}
